# docker-compose.yml
version: "3.9"
services:
  backend:
    build: .
    platform: linux/arm64  # Optional: if you're building for ARM
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql-db
      DB_ENV: dev
      DB_NAME: fapi
      DB_USER: root
      DB_PASSWORD: root     
      DB_PORT: 3306
      ACCESS_TOKEN_SECRET: your_access_token_secret
      REFRESH_TOKEN_SECRET: your_refresh_token_secret
    # Optional: Jika Anda memiliki file .env, Anda bisa menggunakan env_file
    # env_file:
    #   - .env

  db:
    image: mysql:5.7
    platform: linux/amd64  # Forces the x86_64 architecture for MySQL
    container_name: mysql-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 15s
      timeout: 20s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fapi         
    volumes:
      - mysql-persistent-storage:/var/lib/mysql

volumes:
  mysql-persistent-storage:
    driver: local
