version: "3.9"
services:
  backend:
    build: .
    platform: linux/arm64  # Optional: if you're building for ARM
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql-db
      DB_ENV: dev

  db:
    image: mysql:5.7
    platform: linux/amd64  # Forces the x86_64 architecture for MySQL
    container_name: mysql-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root    # Only this variable is necessary for root user
      MYSQL_DATABASE: fapi         # The database to be created
      # Removed MYSQL_USER and MYSQL_PASSWORD
